apiVersion: apps/v1
kind: Deployment
metadata:
  name: colors
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "colors"
  template:
    metadata:
      labels:
        app: "colors"
    spec:
      containers:
      - name: colors
        image: noloknolo/colors:v1
        ports:
        - containerPort: 8080
