apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-ejercicio13
data:
  index.html: |
    <html>
      <head>
        <title>Configmap</title>
      </head>
      <body>
        <h1>Mira mi index, creado con Configmap</h1>
      </body>
    </html>
