apiVersion: apps/v1
kind: Deployment
metadata:
  name: demogat-yaml
spec:
  selector:
    matchLabels:
      app: "gato"
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "gato"
    spec:
      containers:
      - name: tomcat
        image: tomcat:11.0-jre21